def getMyDict():
    extraWords = {
        #Technical
        "ssd" : "solid state drive",
        "hdd" : "hard disk drive",
        "rm" : "ringgit malaysia",
        "tb" : "TERABYTE",
        "gb" : "gigabait",
        "mb" : "megabait",
        "rpm": "revolusi per minit",
        "gbps" : "gigabait per saat",
        "mbps" : "megabit per saat",
        "mbp's" : "megabit per saat",
        "mb's" : "megabait per saat",
        "usb": "USB",
        "gen" : "generasi",
        "pc": "PC",
        "pcs":"PC",
        "dr": "dari",
        "hp": "HANDPHONE",
        "die": "dia",
        #date
        "jan" : "january",
        "feb" : "februari",
        "aprl" : "april",
        "aug" : "august",
        "sept" : "september",
        "oct" : "oktober",
        "nov" : "november",
        "dec": "disember",
        #Company Name
        "ugreen" : "UGREEN",
        "seagate" : "SEAGATE",
        "toshiba": "TOSHIBA",
        #ShortformsMalay
        "smpi": "sampai",
        "sih" : "lah",
        "sec" : "second",
        "cun" : "nice",
        "notik": "notis",
        #Shortform English
        "i've" : "i have",
        "there's" : "there is",
        "can't": "cannot",
        "can'" : "cannot",
        "couldn'": "could not",
        "couldn't": "could not",
        "wouldn'" : "would not",
        "wouldn't" : "would not",
        "it's" : "it is",
        "don't" : "do not",
        "don'" : "do not",
        "th": "day",
        "rd": "",
        "s": "saat",
        "h" : "jam",
        "my" : "saya punya",
        "is" : "ialah",
        "in" : "dalam",
        "on" : "",
        "as" : "seperti",
        "packing" : "bungkusan",
        "packed": "telah dibungkus",
        "didn'" : "did not",
        "didn't": "did not",
        "that's" : "that is",
        "etc" : "et cetera",
        "ps" : "PLAY STATION",
        "ex" : "former",
        "&": "and",
        "superb": "super",
        "k" : " thousand"
        #endDate
    }
    return extraWords
